In [1]:
import numpy as np

Задание 5.1

In [3]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 2], float)

In [13]:
#Скалярное произведение векторов.
c = np.dot(a, b)
print(c)

8.0


In [11]:
d = np.array([[1, 2, 3]], float)
e = d.transpose()

In [12]:
print(e)

[[1.]
 [2.]
 [3.]]


In [14]:
# Векторное произведение.
g = np.dot(d, e)
print(g)

[[14.]]


In [15]:
z = np.dot(e, d)
print(z)

[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


Задание 5.2

In [18]:
a2 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a2)
np.linalg.det(a2)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


59.999999999999986

In [19]:
1*0*9 + 2*6*7 + 3*4*8 - 3*0*7 - 1*6*8 - 2*4*9

60

Задание 5.3

In [20]:
np.linalg.inv(a2)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

Матрица 4*4 с рангом 1

In [22]:
a44 = np.ones((4, 4))
print(a44)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Задание 5.4

In [23]:
v1 = np.array([1, 5])
v2 = np.array([2, 8])
np.dot(v1, v2)

42

Задание 5.5

In [25]:
arr1 = np.array([1, 5, 0])
arr2 = np.array([2, 8, 7])
arr3 = np.array([7, 1.5, 3])
v = np.cross(arr1, arr2)
print(np.inner(v, arr3))

w = np.cross(arr2, arr3)
print(np.inner(w, arr1))

228.5
228.5
